apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-crashloop
    type: test-pod
  name: pod-crashloop
spec:
  containers:
    - image: alpine:3
      name: pod-crashloop
      command:
        - sh
        - "-c"
        - |
          sleep 1
          invalid_command
  dnsPolicy: ClusterFirst
  restartPolicy: Always
