apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-not-enough-resources
    type: test-pod
  name: pod-not-enough-resources
spec:
  containers:
    - image: alpine:3
      name: pod-not-enough-resources
      resources:
        requests:
          cpu: "10000000"
          memory: "100000Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
