apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-create-container-error
    type: test-pod
  name: pod-create-container-error
spec:
  containers:
    - image: alpine:3
      name: pod-create-container-error
      env:
        - name: SOMETHING
          valueFrom:
            configMapKeyRef:
              name: configmap-does-nont-exist
              key: key
  restartPolicy: Always
