apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-outofmemory
    type: test-pod
  name: pod-outofmemory
spec:
  containers:
    - image: python:3.10-alpine
      name: pod-outofmemory
      command:
        - python
        - "-c"
        - |
          ar = bytearray(0)
          while True:
            ar += bytearray(10 ** 10)
      resources:
        requests:
          cpu: 100m
          memory: 4Mi
        limits:
          cpu: 100m
          memory: 4Mi
  restartPolicy: Always
