apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sentry-kubernetes
  name: sentry-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentry-kubernetes
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sentry-kubernetes
    spec:
      containers:
        - image: tonyo/sentry-kubernetes:7caee4eda07fe49a331d0cd3adaae67b625388c3
          name: sentry-kubernetes
          env:
            - name: SENTRY_K8S_LOG_LEVEL
              value: debug
      serviceAccount: sentry-k8s-agent
