---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentry-k8s-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentry-k8s-agent-cluster
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentry-k8s-agent-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sentry-k8s-agent-cluster
subjects:
  - kind: ServiceAccount
    name: sentry-k8s-agent
    namespace: default
