apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sentry-kubernetes
  name: sentry-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentry-kubernetes
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sentry-kubernetes
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/testproj-195619/private/sentry-kubernetes:63fd06227bd96cc10864471bc242a6a141b3e252-dirty
          name: sentry-kubernetes
          env:
            - name: SENTRY_K8S_LOG_LEVEL
              value: debug
            - name: SENTRY_DSN
              # FIXME
              value: ""
            - name: SENTRY_K8S_INTEGRATION_GKE_ENABLED
              value: "1"
      serviceAccount: sentry-k8s-agent
